backend/controllers/NewsController.php
<?php

namespace backend\controllers;

use backend\models\NewsModel;
use Yii;
use common\models\News;
use common\models\search\NewsSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * NewsController implements the CRUD actions for News model.
 */
class NewsController extends Controller
{
    /**
     * @inheritdoc
     */

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['index','create','update','delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all News models.
     * @return mixed
     */
    public function actionIndex()
    {
        $news = NewsModel::get_all();
        return $this->render('index', ['news' => $news]);
    }

    /**
     * Displays a single News model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', ['model' => NewsModel::findModel($id)]);
    }

    /**
     * Creates a new News model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new NewsModel();

        if ($model->load(Yii::$app->request->post())) {
            $save = $model->save_news();
            if ($save === 'redirect') {
                Yii::$app->session->setFlash('error', 'Неверный формат файла');
                return $this->redirect(['create']);
            } elseif ($save) {
                return $this->redirect(['index']);
            } else {
                Yii::$app->session->setFlash('error', 'Не удалось произвести сохранение');
                return $this->redirect(['create']);
            }
        }
        return $this->render('create', ['model' => $model]);
    }

    /**
     * Updates an existing News model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = NewsModel::findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $save = $model->save_news();
            if ($save === 'redirect') {
                Yii::$app->session->setFlash('error', 'Неверный формат файла');
                return $this->redirect(['/news/update/'.$id]);
            } elseif ($save) {
                return $this->redirect(['index']);
            } else {
                Yii::$app->session->setFlash('error', 'Не удалось произвести сохранение');
                return $this->redirect(['/news/update/'.$id]);
            }
        } else {
            return $this->render('update', ['model' => $model]);
        }
    }

    /**
     * Deletes an existing News model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        NewsModel::findModel($id)->delete();
        return $this->redirect(['index']);
    }

}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['index', 'create-order','image-upload','images-get'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'image-upload' => [
                'class' => 'vova07\imperavi\actions\UploadAction',
                'url' => '/storage/web/images/store/news', // Directory URL address, where files are stored.
                'path' => '@imagestore/news' // Or absolute path to directory where files are stored.
            ],
             'images-get' => [
                'class' => 'vova07\imperavi\actions\GetAction',
                'url' => '/storage/web/images/store/news', // Directory URL address, where files are stored.
                'path' => '@imagestore/news', // Or absolute path to directory where files are stored.
                //'type' => GetAction::TYPE_IMAGES,
            ]
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        //return $this->redirect('/backend/web/order/order/create');
        
        return $this->render('index');
    }

}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use app\models\Certificates;
use app\models\Contacts;
use app\models\Page;
use app\models\SliderMain;
use app\models\News;
use app\models\PhotoAndVideo;
use Yii;
use yii\web\Controller;
use pistol88\shop\models\Product;

class SiteController extends Controller
{

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        $slider_main = SliderMain::get_all();
        $products_new = Product::find()->where(['is_new' => 'yes'])->all();
        $recommended = Product::find()->where(['is_popular' => 'yes'])->orderBy('RAND()')->limit('4')->all();
        $main_news = News::get_last_news(3);
        return $this->render('index', [
            'slider_main' => $slider_main,
            'products_new' => $products_new,
            'recommended' => $recommended,
            'news' => $main_news
        ]);
    }

    public function actionFoto_video()
    {
        $content = PhotoAndVideo::get_all();
        return $this->render('foto_video', ['content' => $content]);
    }

    public function actionContact()
    {
        $contacts = Contacts::get_all();
        $title = Contacts::get_title();
        return $this->render('contact', ['contacts' => $contacts, 'title' => $title]);
    }

    public function actionPage($slug)
    {
        $content = Page::get_page_by_slug($slug);
        return $this->render('page', ['content' => $content]);
    }

    public function actionCertificate()
    {
        $certificates = Certificates::get_all();
        return $this->render('certificate', ['certificates' => $certificates]);
    }

    public function actionCart()
    {
        $elements = Yii::$app->cart->elements;
        return $this->render('cart', [
            'elements' => $elements
        ]);
    }

    public function actionThanks()
    {
        return $this->render('thanks');
    }

}

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/index.php
<?php
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'Магазин';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Все системы в норме!</h1>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Витрина</h2>
                <ul>
                    <li><a href="<?=Url::toRoute(['/shop/category/index']);?>">Категории</a></li>
                    <li><a href="<?=Url::toRoute(['/shop/product/index']);?>">Товары</a></li>
                </ul>
            </div>
            <div class="col-lg-4">
                <h2>Информация</h2>
                <ul>
                    <li><a href="<?=Url::toRoute(['/page/index']);?>">Страницы</a></li>
                    <li><a href="<?=Url::toRoute(['/news/index']);?>">Новости</a></li>
                    <li><a href="<?=Url::toRoute(['/slider/index']);?>">Слайдер</a></li>
                    <li><a href="<?=Url::toRoute(['/photovideo/index']);?>">Фото и видео</a></li>
                    <li><a href="<?=Url::toRoute(['/contacts/index']);?>">Контакты</a></li>
                    <li><a href="<?=Url::toRoute(['/certificates/index']);?>">Сертификаты</a></li>
                </ul>
            </div>
            <div class="col-lg-4">
                <h2>Настройки</h2>
                <ul>
                    <li><a href="<?=Url::toRoute(['/field/field/index']);?>">Поля</a></li>
                    <li><a href="<?=Url::toRoute(['/filter/filter/index']);?>">Фильтры</a></li>
                </ul>
            </div>
        </div>

    </div>
</div>